targets = [
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "i686-pc-windows-msvc" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow-osi-fsf-free = "neither"
confidence-threshold = 0.93
default = "deny"
private = { ignore = true }
allow = [ "Apache-2.0", "MIT", "Unlicense", "Unicode-DFS-2016" ]
exceptions = []

[bans]
multiple-versions = "warn"
highlight = "all"
skip = []
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [ "https://github.com/rust-lang/crates.io-index" ]
allow-git = []
