name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deny:
    name: Deny
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deny
        uses: EmbarkStudios/cargo-deny-action@v1

  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download Logitech LED SDK
      run: Invoke-WebRequest -Uri https://www.logitechg.com/sdk/LED_SDK_9.00.zip -OutFile LED_SDK_9.00.zip
    - name: Extract Logitech LED SDK
      run: 7z x LED_SDK_9.00.zip
    - name: Set Logitech LED SDK Location
      run: echo "LOGITECH_LED_SDK=${env:GITHUB_WORKSPACE}/LED" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: Install Scoop
      run: |
        iwr -useb get.scoop.sh | iex
        echo "$($HOME)/scoop/shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Install LLVM
      run: |
        scoop install llvm
        echo "LIBCLANG_PATH=$($HOME)/scoop/apps/llvm/current/bin" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: Build
      run: cargo build --verbose
    # Cannot test on CI as there is no LGS or LGHUB on there. Is it possible to install it?
    # - name: Run Tests
    #   run: cargo test --all --verbose
