name: RustDoc
on:
  push:
    branches:
      - master

jobs:
  rustdoc:
    name: RustDoc
    
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build Documentation
      run: cargo doc --all --no-deps --features=rustdoc

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
        force_orphan: true
